// <auto-generated />
using DowUmg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DowUmg.Migrations.Migrations
{
    [DbContext(typeof(ModsContext))]
    [Migration("20191224065354_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("DowUmg.Data.Entities.DowMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Players")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVanilla")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Playable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsVanilla", "ModFolder");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowModDependency", b =>
                {
                    b.Property<int>("MainModId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepModId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MainModId", "DepModId");

                    b.HasIndex("DepModId");

                    b.ToTable("ModDependencies");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWinCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("GameRules");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowMap", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.DowMod", "Mod")
                        .WithMany("Maps")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowModDependency", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.DowMod", "DepMod")
                        .WithMany("Dependents")
                        .HasForeignKey("DepModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DowUmg.Data.Entities.DowMod", "MainMod")
                        .WithMany("Dependencies")
                        .HasForeignKey("MainModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowRace", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.DowMod", "Mod")
                        .WithMany("Races")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameRule", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.DowMod", "Mod")
                        .WithMany("Rules")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
