// <auto-generated />
using System;
using DowUmg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DowUmg.Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("DowUmg.Data.Entities.Alliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Alliance");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.Army", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AllianceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("CampaignId");

                    b.ToTable("Army");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSingle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Players")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowMod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RandomPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RandomTeams")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResourceRate")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Sharing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartingResources")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameInfo");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameInfoRule", b =>
                {
                    b.Property<int>("InfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfoId", "RuleId");

                    b.HasIndex("RuleId");

                    b.ToTable("GameInfoRule");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWinCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("GameRules");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.SaveGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("SaveGames");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InfoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritedCustomRules")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritedGameOptions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritedGameRules")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritedWinConditions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("InfoId");

                    b.HasIndex("MapId");

                    b.HasIndex("NextId")
                        .IsUnique();

                    b.HasIndex("PreviousId");

                    b.ToTable("Scenario");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.ScenarioPlayers", b =>
                {
                    b.Property<int>("ArmyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArmyId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioPlayers");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.Alliance", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.Campaign", "Campaign")
                        .WithMany("Alliances")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.Army", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.Alliance", "Alliance")
                        .WithMany("Armies")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DowUmg.Data.Entities.Campaign", "Campaign")
                        .WithMany("Armies")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.DowMap", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.DowMod", "Mod")
                        .WithMany("Maps")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameInfo", b =>
                {
                    b.OwnsMany("DowUmg.Data.Entities.CustomRule", "CustomRules", b1 =>
                        {
                            b1.Property<int>("GameInfoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("GameInfoId", "Id");

                            b1.ToTable("CustomRule");

                            b1.WithOwner()
                                .HasForeignKey("GameInfoId");
                        });
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameInfoRule", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.GameInfo", "Info")
                        .WithMany("Rules")
                        .HasForeignKey("InfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DowUmg.Data.Entities.GameRule", "Rule")
                        .WithMany("Infos")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.GameRule", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.DowMod", "Mod")
                        .WithMany("Rules")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.SaveGame", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.Campaign", "Campaign")
                        .WithMany("SaveGames")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DowUmg.Data.Entities.Scenario", "Scenario")
                        .WithMany("SaveGames")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });

            modelBuilder.Entity("DowUmg.Data.Entities.Scenario", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.Campaign", "Campaign")
                        .WithMany("Scenarios")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DowUmg.Data.Entities.GameInfo", "Info")
                        .WithMany()
                        .HasForeignKey("InfoId");

                    b.HasOne("DowUmg.Data.Entities.DowMap", "Map")
                        .WithMany("Scenarios")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("DowUmg.Data.Entities.Scenario", "Next")
                        .WithOne()
                        .HasForeignKey("DowUmg.Data.Entities.Scenario", "NextId");

                    b.HasOne("DowUmg.Data.Entities.Scenario", "Previous")
                        .WithMany()
                        .HasForeignKey("PreviousId");
                });

            modelBuilder.Entity("DowUmg.Data.Entities.ScenarioPlayers", b =>
                {
                    b.HasOne("DowUmg.Data.Entities.Army", "Army")
                        .WithMany("Scenarios")
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DowUmg.Data.Entities.Scenario", "Scenario")
                        .WithMany("Players")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
